(()=>{
'use strict';
const q=new URLSearchParams(location.search),type=q.get('type'),id=q.get('id'),key=(type||'')+':'+(id||'');
const x=window.GBE_DATA?.[key]||['Nicht gefunden','','Diese Detailseite existiert nicht.','Input|Output','—','—','—','',''];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const R=window.SchematicRenderer,sourcePlans=window.GBE_SCHEMATIC_SOURCES?.[key]||[],hasComponent=Boolean(R?.isTrue?.(key)),info=R?.getInfo(key)||null;
function bomRows(s){return String(s).split(';').filter(v=>v.trim()).map(v=>{const part=v.trim(),url=`https://www.google.com/search?q=${encodeURIComponent(part+' Elektronik Bauteil kaufen')}`;return `<tr><td>${esc(part)}</td><td><a class="part-search" href="${url}" target="_blank" rel="noopener noreferrer" aria-label="${esc(part)} suchen">Bauteil suchen ↗</a></td></tr>`}).join('')}
function waveform(){let out='M0 45C10 20 23 16 34 29S57 72 72 58S96 16 111 31S137 72 150 45';if(type==='wiring'||type==='pickup'||type==='body')out='M0 45C12 12 25 12 37 45S62 78 75 45S100 12 112 45S137 78 150 45';if(type==='amp')out='M0 45C10 10 25 10 36 28L43 28C50 30 52 39 55 45C64 70 72 75 82 68C94 60 98 50 102 42C110 19 123 11 135 22C142 29 146 38 150 45';return `<svg class="wave" viewBox="0 0 150 90"><line class="axis" x1="0" y1="45" x2="150" y2="45"/><path class="in" d="M0 45C12 12 25 12 37 45S62 78 75 45S100 12 112 45S137 78 150 45"/><path class="out" d="${out}"/></svg>`}
function icon(){if(type==='pickup')return `<svg class="icon" viewBox="0 0 120 100"><rect x="15" y="31" width="90" height="38" rx="8" fill="#6e6d79"/>${[30,42,54,66,78,90].map(cx=>`<circle cx="${cx}" cy="50" r="4" fill="#ddd"/>`).join('')}</svg>`;if(type==='amp')return `<svg class="icon" viewBox="0 0 120 100"><rect x="10" y="18" width="100" height="66" rx="8" fill="#353c44"/><rect x="18" y="26" width="84" height="15" rx="3" fill="#161b20"/><circle cx="60" cy="63" r="18" fill="#161b20" stroke="#77838e"/></svg>`;if(type==='body')return `<svg class="icon" viewBox="0 0 120 100"><path d="M26 18c17-9 28 5 34 16 8-12 22-20 34-9 10 10 2 24-8 30 13 16 8 32-7 36-13 4-23-7-25-17-6 11-19 18-29 10-10-8-5-24 5-32-10-8-14-25-4-34z" fill="#46525d"/></svg>`;return `<svg class="icon" viewBox="0 0 120 100"><rect x="18" y="12" width="84" height="74" rx="10" fill="#35404a"/><circle cx="42" cy="35" r="8" fill="#111820"/><circle cx="78" cy="35" r="8" fill="#111820"/><circle cx="60" cy="67" r="9" fill="#d6dde1"/></svg>`}
function refs(plans){if(!plans.length)return'';return `<div class="reference-links">${plans.map(p=>`<p><b>${esc(p.label)}</b><br>${esc(p.publisher)} · ${esc(p.revision)}</p>`).join('')}</div>`}
R?.prepare?.(key);
const schematic=R?.render(key,x)||'',blockSchematic=hasComponent?(R?.renderBlock(x)||''):'',schematicHeading=hasComponent?'Komponenten-Schaltplan':'Funktionsübersicht';
const schematicNote=hasComponent?'Lokaler, interaktiver Komponentenplan. Antippen oder doppelklicken öffnet die große Ansicht. Bauteile können als Offen, In Arbeit oder Fertig markiert werden.':'Bauteildaten und Aufbau sind erfasst. Der Komponenten-Schaltplan bleibt als Funktionsübersicht markiert, bis eine belastbare Vorlage geprüft wurde.';
const statusSection=hasComponent?`<div class="box full"><h3>Stückliste / Lötstatus</h3>${R.trackerHTML()}<div style="overflow:auto;margin-top:14px"><table class="bom component-status-table"><thead><tr><th>ID</th><th>Bauteil</th><th>Wert / Typ</th><th>Status</th></tr></thead><tbody>${R.componentRows()}</tbody></table></div></div>`:`<div class="box full"><h3>Materialliste / BOM</h3><div style="overflow:auto"><table class="bom"><tbody>${bomRows(x[4])}</tbody></table></div></div>`;
const variant=info?.variant||x[8]||'',reference=info?.reference||x[7]||'Technische Referenzdaten; vor dem Aufbau Datenblätter und Pinouts der tatsächlich verwendeten Bauteile prüfen.';
const status=hasComponent?'Interaktiver Komponentenplan verfügbar':'Daten/BOM erfasst · Komponentenplan noch in Prüfung';
document.title=`${x[0]} · ToneForge Workshop`;
document.getElementById('content').innerHTML=`<div class="detail-top"><div><span class="ey">${esc(x[1])}</span><h1>${esc(x[0])}</h1><p class="lead">${esc(x[2])}</p><div class="detail-toolstrip"><button type="button" data-detail-favorite>★ <span>Favorit</span></button><button type="button" data-detail-share>↗ <span>Teilen</span></button><button type="button" data-export-bom>↓ <span>BOM exportieren</span></button><button type="button" data-wake-lock>☼ <span>Display anlassen</span></button></div></div><div class="bigvis">${icon()}${waveform()}</div></div><div class="boxes"><div class="box full"><h3>${schematicHeading}</h3><div class="schem">${schematic}</div><p class="${hasComponent?'schem-caption':'schem-warning'}">${schematicNote}</p></div>${blockSchematic?`<div class="box full block-overview"><h3>Blockschaltbild / Signalfluss</h3><div class="block-schem">${blockSchematic}</div><p>Ergänzende Übersicht über die Verarbeitungsschritte.</p></div>`:''}${statusSection}<div class="box"><h3>Kostenüberschlag</h3><div class="cost">${esc(x[5])}</div><p>Grobe DIY-Spanne, abhängig von Händler, Gehäuse und vorhandenen Teilen.</p></div><div class="box"><h3>Bauhinweise</h3><p>${esc(x[6])}</p></div><div class="box full"><h3>Beschreibung / Aufbau</h3><p>${esc(x[2])}</p><p><b>Signalweg:</b> ${String(x[3]).split('|').map(esc).join(' → ')}</p>${variant?`<p><b>Referenzvariante:</b> ${esc(variant)}</p>`:''}</div><div class="box full detail-notes"><h3>Werkstattnotizen</h3><textarea data-project-note placeholder="Messwerte, Änderungen, Bauteilvarianten, Fehler und Ideen …"></textarea><small>Automatisch lokal gespeichert · wird im Workspace-Backup mit exportiert</small></div><div class="box full"><h3>Datenstand / Referenzen</h3><p><b>Status:</b> ${esc(status)}</p><p>${esc(reference)}</p>${refs(sourcePlans)}<p class="schem-warning">Hersteller-Pinouts, Polaritäten und Bauteilrevisionen vor dem Löten immer gegen das konkrete Datenblatt prüfen. Bei Netzspannung und Röhrenverstärkern gelten zusätzliche Sicherheitsanforderungen.</p></div></div>`;
if(hasComponent)R.initTracker(key);
window.ToneForgeDetail={key,type,id,data:x,hasComponent};
})();
