(()=>{
'use strict';
const q=new URLSearchParams(location.search),type=q.get('type'),id=q.get('id'),key=(type||'')+':'+(id||'');
const x=window.GBE_DATA?.[key]||['Nicht gefunden','','Diese Detailseite existiert nicht.','Input|Output','—','—','—','',''];
const plans=window.GBE_SCHEMATIC_SOURCES?.[key]||[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const requirement={pedal:'Elektrischer Schaltplan',amp:'Elektrischer Schaltplan / Service-Schematic',wiring:'Verdrahtungsplan',pickup:'Wicklungs-/Konstruktionsplan + Verdrahtung',instrument:'Elektrischer Schaltplan',body:'CAD-/Maßzeichnung'}[type]||'Technische Zeichnung';
const trustLabels={manufacturer:'HERSTELLER','service-copy':'SERVICE-UNTERLAGE','open-source':'OPEN SOURCE','established-diy':'ETABLIERTE DIY-QUELLE',datasheet:'DATENBLATT',reference:'REFERENZ'};
const reviewLabels={verified:'VERIFIZIERT',crosschecked:'GEGENGEPRÜFT','source-found':'QUELLE GEFUNDEN',candidate:'KANDIDAT'};
function bomRows(s){return String(s).split(';').filter(v=>v.trim()).map(v=>{const part=v.trim(),url=`https://www.google.com/search?q=${encodeURIComponent(part+' Elektronik Bauteil kaufen')}`;return `<tr><td>${esc(part)}</td><td><a class="part-search" href="${url}" target="_blank" rel="noopener noreferrer">Bauteil suchen ↗</a></td></tr>`}).join('')}
function waveform(){let out='M0 45C10 20 23 16 34 29S57 72 72 58S96 16 111 31S137 72 150 45';if(type==='wiring'||type==='pickup'||type==='body')out='M0 45C12 12 25 12 37 45S62 78 75 45S100 12 112 45S137 78 150 45';if(type==='amp')out='M0 45C10 10 25 10 36 28L43 28C50 30 52 39 55 45C64 70 72 75 82 68C94 60 98 50 102 42C110 19 123 11 135 22C142 29 146 38 150 45';return `<svg class="wave" viewBox="0 0 150 90"><line class="axis" x1="0" y1="45" x2="150" y2="45"/><path class="in" d="M0 45C12 12 25 12 37 45S62 78 75 45S100 12 112 45S137 78 150 45"/><path class="out" d="${out}"/></svg>`}
function icon(){if(type==='pickup')return `<svg class="icon" viewBox="0 0 120 100"><rect x="15" y="31" width="90" height="38" rx="8" fill="#6e6d79"/>${[30,42,54,66,78,90].map(cx=>`<circle cx="${cx}" cy="50" r="4" fill="#ddd"/>`).join('')}</svg>`;if(type==='amp')return `<svg class="icon" viewBox="0 0 120 100"><rect x="10" y="18" width="100" height="66" rx="8" fill="#353c44"/><rect x="18" y="26" width="84" height="15" rx="3" fill="#161b20"/><circle cx="60" cy="63" r="18" fill="#161b20" stroke="#77838e"/></svg>`;if(type==='body')return `<svg class="icon" viewBox="0 0 120 100"><path d="M26 18c17-9 28 5 34 16 8-12 22-20 34-9 10 10 2 24-8 30 13 16 8 32-7 36-13 4-23-7-25-17-6 11-19 18-29 10-10-8-5-24 5-32-10-8-14-25-4-34z" fill="#46525d"/></svg>`;return `<svg class="icon" viewBox="0 0 120 100"><rect x="18" y="12" width="84" height="74" rx="10" fill="#35404a"/><circle cx="42" cy="35" r="8" fill="#111820"/><circle cx="78" cy="35" r="8" fill="#111820"/><circle cx="60" cy="67" r="9" fill="#d6dde1"/></svg>`}
function planCard(p,i){const image=p.image||'',source=p.source||image,trust=trustLabels[p.trust]||trustLabels.reference,review=reviewLabels[p.review]||reviewLabels['source-found'];return `<article class="source-plan-card" data-review="${esc(p.review||'source-found')}"><div class="source-plan-head"><div><div class="source-plan-badges"><span class="source-plan-badge">${esc(trust)}</span><span class="source-plan-review">${esc(review)}</span></div><h4>${esc(p.label||`${requirement} ${i+1}`)}</h4><p>${esc(p.publisher||'Referenzquelle')}${p.revision?` · ${esc(p.revision)}`:''}</p>${p.note?`<p class="source-plan-note">${esc(p.note)}</p>`:''}</div><div class="source-plan-actions">${source?`<a href="${esc(source)}" target="_blank" rel="noopener noreferrer">Quelle öffnen ↗</a>`:''}${image?`<a href="${esc(image)}" target="_blank" rel="noopener noreferrer">Originalgrafik ↗</a>`:''}</div></div>${image?`<a class="plan-stage" data-project="${esc(key)}" data-plan-index="${i}" href="${esc(image)}" target="_blank" rel="noopener noreferrer"><img src="${esc(image)}" alt="${esc(p.label||requirement)}" loading="eager" decoding="async"><svg class="plan-annotation-surface" viewBox="0 0 1000 1000" preserveAspectRatio="none" aria-hidden="true"></svg><span class="plan-open-hint">Originalgröße öffnen</span><span class="plan-load-error" hidden>Einbettung blockiert. Quelle öffnen.</span></a>`:`<div class="source-plan-linkonly"><b>Schaltplan liegt bei der Quelle.</b><p>Aus Lizenz-, Hotlink- oder Dateiformatgründen wird hier keine Kopie eingebettet.</p>${source?`<a href="${esc(source)}" target="_blank" rel="noopener noreferrer">${esc(requirement)} öffnen ↗</a>`:''}</div>`}</article>`}
function technicalSection(){if(plans.length)return `<div class="box full source-schematic-box"><div class="schematic-priority-head"><div><span class="ey">PRIORITÄT 1</span><h3>${esc(requirement)}</h3></div><strong>${plans.length} Quelle${plans.length===1?'':'n'}</strong></div><p class="schematic-definition">ToneForge zeichnet hier nichts selbst nach. Die Einträge verweisen auf Hersteller-, Service-, Datenblatt-, Open-Source- oder etablierte Referenzunterlagen. Nur explizit als VERIFIZIERT markierte Einträge gelten als vollständig elektrisch geprüft.</p><div class="source-plan-list">${plans.map(planCard).join('')}</div></div>`;return `<div class="box full source-schematic-box"><div class="schematic-priority-head"><div><span class="ey">PRIORITÄT 1</span><h3>${esc(requirement)}</h3></div><strong class="missing">FEHLT</strong></div><div class="schematic-missing"><b>Noch keine belastbare Quelle hinterlegt.</b><p>Kein Blockschaltbild und keine Eigenzeichnung wird als Ersatz ausgegeben. Dieses Projekt bleibt offen, bis eine konkrete Revision und eine geeignete technische Quelle feststehen.</p></div></div>`}
function blockSection(){const stages=String(x[3]||'').split('|').map(s=>s.trim()).filter(Boolean);if(!stages.length)return'';return `<div class="box full block-overview signal-flow-only"><div class="schematic-priority-head"><div><span class="ey">ZUSATZGRAFIK</span><h3>Blockschaltbild / Signalfluss</h3></div><strong>ÜBERSICHT</strong></div><p class="block-definition">Nur zur Orientierung. Dieses Diagramm ersetzt ausdrücklich keinen Schalt- oder Verdrahtungsplan.</p><div class="signal-flow-blocks">${stages.map((s,i)=>`${i?'<span class="flow-arrow" aria-hidden="true">→</span>':''}<div class="flow-block">${esc(s)}</div>`).join('')}</div></div>`}
const variant=x[8]||'',reference=x[7]||'Technische Grunddaten vorhanden; konkrete Revision und Quelle müssen vor dem Aufbau geprüft werden.';
const reviewState=plans.some(p=>p.review==='verified')?'Mindestens eine Quelle verifiziert':plans.some(p=>p.review==='crosschecked')?'Mindestens eine Quelle gegengeprüft':plans.length?'Quelle(n) gefunden · elektrische Verifikation noch offen':'Technische Hauptunterlage fehlt';
document.title=`${x[0]} · ToneForge Workshop`;
document.getElementById('content').innerHTML=`<div class="detail-top"><div><span class="ey">${esc(x[1])}</span><h1>${esc(x[0])}</h1><p class="lead">${esc(x[2])}</p><div class="detail-toolstrip"><button type="button" data-detail-favorite>★ <span>Favorit</span></button><button type="button" data-detail-share>↗ <span>Teilen</span></button><button type="button" data-export-bom>↓ <span>BOM exportieren</span></button><button type="button" data-wake-lock>☼ <span>Display anlassen</span></button></div></div><div class="bigvis">${icon()}${waveform()}</div></div><div class="boxes">${technicalSection()}${blockSection()}<div class="box full"><h3>Materialliste / BOM</h3><div style="overflow:auto"><table class="bom"><tbody>${bomRows(x[4])}</tbody></table></div></div><div class="box"><h3>Kostenüberschlag</h3><div class="cost">${esc(x[5])}</div><p>Grobe DIY-Spanne, abhängig von Händler, Gehäuse und vorhandenen Teilen.</p></div><div class="box"><h3>Bauhinweise</h3><p>${esc(x[6])}</p></div><div class="box full"><h3>Beschreibung / Aufbau</h3><p>${esc(x[2])}</p><p><b>Signalweg:</b> ${String(x[3]).split('|').map(esc).join(' → ')}</p>${variant?`<p><b>Projektvariante:</b> ${esc(variant)}</p>`:''}</div><div class="box full detail-notes"><h3>Werkstattnotizen</h3><textarea data-project-note placeholder="Messwerte, Änderungen, Bauteilvarianten, Fehler und Ideen …"></textarea><small>Automatisch lokal gespeichert · wird im Workspace-Backup mit exportiert</small></div><div class="box full"><h3>Prüfstatus</h3><p><b>Geforderte Hauptunterlage:</b> ${esc(requirement)}</p><p><b>Status:</b> ${esc(reviewState)}</p><p>${esc(reference)}</p><p class="schem-warning">Vor dem Löten immer konkrete Revision, Pinouts, Polaritäten, Versorgung und BOM gegeneinander prüfen. Bei Netzspannung und Röhrenverstärkern gelten zusätzliche Sicherheitsanforderungen.</p></div></div>`;
document.querySelectorAll('.plan-stage img').forEach(img=>img.addEventListener('error',()=>{img.hidden=true;img.closest('.plan-stage')?.querySelector('.plan-load-error')?.removeAttribute('hidden')}));
window.ToneForgeDetail={key,type,id,data:x,hasComponent:false,plans,requirement};
})();
