(()=>{
'use strict';
const q=new URLSearchParams(location.search),type=q.get('type'),id=q.get('id'),key=(type||'')+':'+(id||'');
const x=window.GBE_DATA?.[key]||['Nicht gefunden','','Diese Detailseite existiert nicht.','Input|Output','—','—','—','',''];
const plans=window.GBE_SCHEMATIC_SOURCES?.[key]||[],media=window.ToneForgeMedia?.[key]||null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const requirement={pedal:'Elektrischer Schaltplan',amp:'Elektrischer Schaltplan / Service-Schematic',wiring:'Verdrahtungsplan',pickup:'Wicklungs-/Konstruktionsplan + Verdrahtung',instrument:'Elektrischer Schaltplan',body:'CAD-/Maßzeichnung'}[type]||'Technische Zeichnung';
const trustLabels={manufacturer:'HERSTELLER','service-copy':'SERVICE-UNTERLAGE','open-source':'OPEN SOURCE','established-diy':'ETABLIERTE DIY-QUELLE',datasheet:'DATENBLATT',reference:'REFERENZ'};
const reviewLabels={verified:'VERIFIZIERT',crosschecked:'GEGENGEPRÜFT','source-found':'QUELLE GEFUNDEN',candidate:'KANDIDAT'};
const standardOf=p=>p.standard||(/europ|iec/i.test(p.layout||'')?'IEC':/amer|ansi/i.test(p.layout||'')?'ANSI':p.layout||'Referenz');
function bomRows(s){return String(s).split(';').filter(v=>v.trim()).map(v=>{const part=v.trim(),url=`https://www.google.com/search?q=${encodeURIComponent(part+' Elektronik Bauteil kaufen')}`;return `<tr><td>${esc(part)}</td><td><a class="part-search" href="${url}" target="_blank" rel="noopener noreferrer">Bauteil suchen ↗</a></td></tr>`}).join('')}
function planCard(p,i){const image=p.image||'',source=p.source||image,trust=trustLabels[p.trust]||trustLabels.reference,review=reviewLabels[p.review]||reviewLabels['source-found'],standard=standardOf(p);return `<article class="source-plan-card" data-review="${esc(p.review||'source-found')}" data-standard="${esc(standard)}"><div class="source-plan-head"><div><div class="source-plan-badges"><span class="source-plan-badge">${esc(trust)}</span><span class="source-plan-review">${esc(review)}</span><span class="source-plan-badge">${esc(standard)}</span></div><h4>${esc(p.label||`${requirement} ${i+1}`)}</h4><p>${esc(p.publisher||'Referenzquelle')}${p.revision?` · ${esc(p.revision)}`:''}</p>${p.note?`<p class="source-plan-note">${esc(p.note)}</p>`:''}</div><div class="source-plan-actions">${source?`<a href="${esc(source)}" target="_blank" rel="noopener noreferrer">Quelle ↗</a>`:''}</div></div>${image?`<button class="plan-stage" type="button" aria-label="${esc(p.label||requirement)} vergrößern"><img src="${esc(image)}" alt="${esc(p.label||requirement)}" loading="eager" decoding="async"><span class="plan-open-hint">Zum Vergrößern öffnen</span><span class="plan-load-error" hidden>Vorschau blockiert – Quelle öffnen.</span></button>`:`<div class="source-plan-linkonly"><b>Der Plan liegt bei der Quelle.</b><p>Aus Lizenz-, Hotlink- oder Dateiformatgründen wird hier keine Kopie eingebettet.</p>${source?`<a href="${esc(source)}" target="_blank" rel="noopener noreferrer">${esc(requirement)} öffnen ↗</a>`:''}</div>`}</article>`}
function technicalSection(){if(!plans.length)return `<section class="box full source-schematic-box"><div class="schematic-priority-head"><div><span class="ey">Priorität 1</span><h3>${esc(requirement)}</h3></div><strong class="missing">FEHLT</strong></div><div class="schematic-missing"><b>Noch keine belastbare technische Quelle hinterlegt.</b><p>Kein Blockschaltbild und keine Eigenzeichnung wird als Ersatz ausgegeben. Das Projekt bleibt offen, bis Revision und Quelle eindeutig feststehen.</p></div></section>`;const standards=[...new Set(plans.map(standardOf))],switcher=standards.length>1?`<div class="standard-switch" aria-label="Schaltplanstandard">${standards.map((s,i)=>`<button type="button" class="${i===0?'active':''}" data-plan-standard="${esc(s)}">${esc(s)}</button>`).join('')}</div>`:'';return `<section class="box full source-schematic-box"><div class="schematic-priority-head"><div><span class="ey">Priorität 1</span><h3>${esc(requirement)}</h3></div><strong>${plans.length} Quelle${plans.length===1?'':'n'}</strong></div><p class="schematic-definition">Nur reale Hersteller-, Service-, Datenblatt-, Open-Source- oder etablierte Referenzunterlagen. Eine Quelle ist erst dann „verifiziert“, wenn Revision, BOM und elektrische Topologie gegengeprüft wurden.</p>${switcher}<div class="source-plan-list">${plans.map(planCard).join('')}</div></section>`}
function blockSection(){const stages=String(x[3]||'').split('|').map(s=>s.trim()).filter(Boolean);if(!stages.length)return'';return `<section class="box full signal-flow-only"><div class="schematic-priority-head"><div><span class="ey">Zusatzgrafik</span><h3>Signalfluss</h3></div><strong>ÜBERSICHT</strong></div><p class="block-definition">Nur zur Orientierung – ausdrücklich kein Ersatz für den elektrischen Schaltplan.</p><div class="signal-flow-blocks">${stages.map((s,i)=>`${i?'<span class="flow-arrow" aria-hidden="true">→</span>':''}<div class="flow-block">${esc(s)}</div>`).join('')}</div></section>`}
const variant=x[8]||'',reference=x[7]||'Technische Grunddaten vorhanden; konkrete Revision und Quelle müssen vor dem Aufbau geprüft werden.';
const reviewState=plans.some(p=>p.review==='verified')?'Mindestens eine Quelle verifiziert':plans.some(p=>p.review==='crosschecked')?'Mindestens eine Quelle gegengeprüft':plans.length?'Quelle gefunden · elektrische Verifikation noch offen':'Technische Hauptunterlage fehlt';
const product=media?.photo?`<aside class="detail-product"><a href="${esc(media.source||media.photo)}" target="_blank" rel="noopener noreferrer"><img src="${esc(media.photo)}" alt="${esc(x[0])}" loading="eager" decoding="async"></a><small>${esc(media.credit||'Produktfoto · externe Quelle')}</small></aside>`:'';
document.title=`${x[0]} · ToneForge Workshop`;
document.getElementById('content').innerHTML=`<header class="detail-top"><div class="detail-title"><span class="ey">${esc(x[1])}</span><h1>${esc(x[0])}</h1><p class="lead">${esc(x[2])}</p><div class="detail-meta"><span>${esc(requirement)}</span><span>${esc(reviewState)}</span>${plans[0]?.revision?`<span>Revision: ${esc(plans[0].revision)}</span>`:''}</div><div class="detail-toolstrip"><button type="button" data-detail-favorite>★ <span>Favorit</span></button><button type="button" data-export-bom>↓ <span>BOM exportieren</span></button></div></div>${product}</header><div class="boxes">${technicalSection()}<section class="box full"><h3>Materialliste / BOM</h3><div style="overflow:auto"><table class="bom"><tbody>${bomRows(x[4])}</tbody></table></div></section><section class="box"><h3>Kostenüberschlag</h3><div class="cost">${esc(x[5])}</div><p>Grobe DIY-Spanne – abhängig von Händler, Gehäuse und vorhandenen Teilen.</p></section><section class="box"><h3>Bauhinweise</h3><p>${esc(x[6])}</p></section><section class="box full"><h3>Beschreibung / Aufbau</h3><p>${esc(x[2])}</p>${variant?`<p><b>Projektvariante:</b> ${esc(variant)}</p>`:''}</section>${blockSection()}<section class="box full detail-notes"><h3>Werkstattnotizen</h3><textarea data-project-note placeholder="Messwerte, Änderungen, Bauteilvarianten, Fehler und Ideen …"></textarea><small>Automatisch lokal im Browser gespeichert.</small></section><section class="box full"><h3>Prüfstatus</h3><p><b>Geforderte Hauptunterlage:</b> ${esc(requirement)}</p><p><b>Status:</b> ${esc(reviewState)}</p><p>${esc(reference)}</p><p class="schem-warning">Vor dem Löten konkrete Revision, Pinouts, Polaritäten, Versorgung und BOM gegeneinander prüfen. Bei Netzspannung und Röhrenverstärkern gelten zusätzliche Hochvolt-Sicherheitsanforderungen.</p></section></div>`;
document.querySelectorAll('.plan-stage img,.detail-product img').forEach(img=>img.addEventListener('error',()=>{img.hidden=true;img.closest('.plan-stage')?.querySelector('.plan-load-error')?.removeAttribute('hidden')}));
const standards=[...new Set(plans.map(standardOf))];if(standards.length>1){const show=std=>{document.querySelectorAll('[data-plan-standard]').forEach(b=>b.classList.toggle('active',b.dataset.planStandard===std));document.querySelectorAll('.source-plan-card').forEach(card=>card.hidden=card.dataset.standard!==std)};show(standards[0]);document.addEventListener('click',e=>{const b=e.target.closest('[data-plan-standard]');if(b)show(b.dataset.planStandard)})}
window.ToneForgeDetail={key,type,id,data:x,hasComponent:false,plans,requirement};
})();