(()=>{
'use strict';
const L=window.ToneForgeLibrary,S=window.ToneForgeState,M=window.ToneForgeMedia||{},P=window.GBE_SCHEMATIC_SOURCES||{};
if(!L||!S)return;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const iconSvg=type=>({pedal:'<rect x="26" y="15" width="68" height="90" rx="14"/><circle cx="48" cy="44" r="8"/><circle cx="72" cy="44" r="8"/><circle cx="60" cy="82" r="10"/>',amp:'<rect x="15" y="23" width="90" height="74" rx="10"/><rect x="25" y="34" width="70" height="14" rx="4"/><circle cx="60" cy="73" r="20"/>',wiring:'<circle cx="25" cy="60" r="8"/><circle cx="95" cy="60" r="8"/><path d="M33 60h13l7-17 15 34 9-17h10"/>',pickup:'<rect x="16" y="39" width="88" height="42" rx="10"/><circle cx="32" cy="60" r="4"/><circle cx="44" cy="60" r="4"/><circle cx="56" cy="60" r="4"/><circle cx="68" cy="60" r="4"/><circle cx="80" cy="60" r="4"/><circle cx="92" cy="60" r="4"/>',instrument:'<path d="M24 83V35l22-10v58M46 42h46v41M18 83h82"/><circle cx="77" cy="45" r="7"/>',body:'<path d="M28 26c16-10 28 5 34 15 7-12 21-21 34-11 11 9 4 25-8 31 13 16 8 35-7 39-14 4-25-8-27-18-5 12-19 22-31 14-12-8-8-27 4-37-12-8-14-24 1-33z"/>'}[type]||'<circle cx="60" cy="60" r="36"/>');
function thumb(item){const media=M[item.key];if(media?.photo)return `<div class="project-thumb has-photo"><img src="${esc(media.photo)}" alt="${esc(item.name)}" loading="lazy" decoding="async"><span class="photo-fallback" hidden>Foto nicht geladen</span></div>`;return `<div class="project-thumb placeholder"><svg viewBox="0 0 120 120" aria-hidden="true">${iconSvg(item.type)}</svg><small>Foto folgt</small></div>`}
function planState(item){const plans=P[item.key]||[];if(!plans.length)return '<span class="plan-state open">Plan offen</span>';if(plans.some(x=>x.review==='verified'))return '<span class="plan-state verified">Verifiziert</span>';return '<span class="plan-state found">Quelle gefunden</span>'}
function card(item){const fav=S.isFavorite(item.key),media=M[item.key];return `<article class="project-card" data-search-card data-key="${esc(item.key)}" data-name="${esc((item.name+' '+item.kind+' '+item.meta).toLowerCase())}"><a class="project-link" href="detail2.html?type=${encodeURIComponent(item.type)}&id=${encodeURIComponent(item.id)}">${thumb(item)}<div class="project-copy"><div class="project-kicker"><span>${esc(item.kind)}</span>${planState(item)}</div><h3>${esc(item.name)}</h3><p>${esc(item.meta)}</p><div class="project-footer"><span>Projekt öffnen →</span>${media?.source?`<small>Produktfoto extern</small>`:''}</div></div></a><button class="favorite-button ${fav?'active':''}" type="button" data-favorite="${esc(item.key)}" aria-label="${fav?'Favorit entfernen':'Als Favorit speichern'}" title="Favorit">★</button></article>`}
function renderLibrary(){const host=$('[data-library-categories]'),pills=$('[data-category-pills]');pills.innerHTML=['all','favorites',...L.categories.map(c=>c.id)].map((id,i)=>`<button type="button" class="category-pill ${i===0?'active':''}" data-filter="${id}">${id==='all'?'Alle':id==='favorites'?'★ Favoriten':esc(L.categories.find(c=>c.id===id)?.label||id)}</button>`).join('');host.innerHTML=L.categories.map(c=>`<section class="library-category" id="${c.id}" data-category="${c.id}"><div class="category-head"><div><span class="ey">${esc(c.eyebrow)}</span><h3>${esc(c.label)}</h3></div><span>${c.items.length}</span></div><div class="project-grid">${L.all.filter(x=>x.category===c.id).map(card).join('')}</div></section>`).join('');$$('.project-thumb img').forEach(img=>img.addEventListener('error',()=>{img.hidden=true;img.parentElement?.querySelector('.photo-fallback')?.removeAttribute('hidden')}))}
function compactCard(item){const media=M[item.key];return `<a class="compact-project" href="detail2.html?type=${encodeURIComponent(item.type)}&id=${encodeURIComponent(item.id)}">${media?.photo?`<img src="${esc(media.photo)}" alt="">`:`<span class="mini-icon"><svg viewBox="0 0 120 120">${iconSvg(item.type)}</svg></span>`}<span><b>${esc(item.name)}</b><small>${esc(item.kind)}</small></span><i>→</i></a>`}
function renderRecent(){const items=S.recent().map(r=>L.all.find(x=>x.key===r.key)).filter(Boolean),sec=$('[data-recent-section]');sec.hidden=!items.length;if(items.length)$('[data-recent-list]').innerHTML=items.map(compactCard).join('')}
function renderFavorites(){const items=S.favorites().map(k=>L.all.find(x=>x.key===k)).filter(Boolean),sec=$('[data-favorites-section]');sec.hidden=!items.length;$('[data-favorites-count]').textContent=`${items.length} gespeichert`;if(items.length)$('[data-favorites-list]').innerHTML=items.map(compactCard).join('')}
function renderInventory(){const inv=S.inventory(),host=$('[data-component-list]');host.innerHTML=L.components.map(([id,name,desc])=>`<article class="component" data-component-search="${esc((name+' '+desc).toLowerCase())}"><div><b>${esc(name)}</b><span>${esc(desc)}</span></div><div class="stock-control"><button type="button" data-stock="${id}" data-delta="-1" aria-label="Eins abziehen">−</button><input type="number" min="0" value="${Number(inv[id]||0)}" data-stock-input="${id}" aria-label="Menge ${esc(name)}"><button type="button" data-stock="${id}" data-delta="1" aria-label="Eins hinzufügen">+</button></div></article>`).join('');updateStats()}
function updateStats(){const inv=S.inventory(),progress=S.projectProgress(),den=Math.max(progress.total,progress.done+progress.active),pct=den?Math.round(progress.done/den*100):0;$('[data-stat-projects]').textContent=L.all.length;$('[data-stat-favorites]').textContent=S.favorites().length;$('[data-stat-progress]').textContent=`${pct}%`;$('[data-stat-progress-label]').textContent=progress.done||progress.active?`${progress.done} fertig · ${progress.active} aktiv`:'noch kein Build';$('[data-stat-stock]').textContent=Object.values(inv).reduce((a,b)=>a+(Number(b)||0),0);$('[data-inventory-total]').textContent=`${Object.keys(inv).length} Gruppen mit Bestand`}
function toast(msg){const el=$('[data-toast]');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1800)}
function applyTheme(){document.documentElement.dataset.theme=S.settings().theme||'dark'}
function toggleTheme(){const next=S.settings().theme==='light'?'dark':'light';S.patchSettings({theme:next});applyTheme()}
function filterLibrary(mode='all'){const query=$('[data-library-search]').value.trim().toLowerCase();let visible=0;$$('.library-category').forEach(sec=>{let count=0;$$('[data-search-card]',sec).forEach(el=>{const matchText=!query||el.dataset.name.includes(query),matchMode=mode==='all'||mode===sec.dataset.category||(mode==='favorites'&&S.isFavorite(el.dataset.key));el.hidden=!(matchText&&matchMode);if(!el.hidden){count++;visible++}});sec.hidden=count===0});$$('.component').forEach(el=>{el.hidden=Boolean(query)&&!el.dataset.componentSearch.includes(query)});$('[data-search-summary]').textContent=query?`${visible} Projekt${visible===1?'':'e'} gefunden`:'Alle Projekte durchsuchen oder filtern.';$('[data-clear-search]').hidden=!query}
function exportWorkspace(){S.download(`toneforge-workspace-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(S.exportWorkspace(),null,2));toast('Workspace exportiert')}
async function importWorkspace(file){try{S.importWorkspace(JSON.parse(await file.text()));renderRecent();renderFavorites();renderInventory();syncFavorites();applyTheme();toast('Workspace wiederhergestellt')}catch(e){toast(e.message||'Import fehlgeschlagen')}}
function syncFavorites(){$$('[data-favorite]').forEach(b=>{const on=S.isFavorite(b.dataset.favorite);b.classList.toggle('active',on);b.setAttribute('aria-label',on?'Favorit entfernen':'Als Favorit speichern')});updateStats()}
renderLibrary();renderRecent();renderFavorites();renderInventory();applyTheme();
document.addEventListener('click',e=>{const fav=e.target.closest('[data-favorite]');if(fav){e.preventDefault();e.stopPropagation();const on=S.toggleFavorite(fav.dataset.favorite);syncFavorites();renderFavorites();toast(on?'Favorit gespeichert':'Favorit entfernt');return}const stock=e.target.closest('[data-stock]');if(stock){const input=$(`[data-stock-input="${stock.dataset.stock}"]`);input.value=S.setInventory(stock.dataset.stock,(Number(input.value)||0)+Number(stock.dataset.delta));updateStats();return}const pill=e.target.closest('[data-filter]');if(pill){$$('[data-filter]').forEach(x=>x.classList.toggle('active',x===pill));filterLibrary(pill.dataset.filter);return}if(e.target.closest('[data-theme-toggle]'))toggleTheme();if(e.target.closest('[data-export-workspace]'))exportWorkspace();if(e.target.closest('[data-import-workspace]'))$('[data-import-file]').click();if(e.target.closest('[data-clear-recent]')){S.write(S.KEYS.recent,[]);renderRecent();toast('Verlauf geleert')}});
$('[data-component-list]').addEventListener('change',e=>{const input=e.target.closest('[data-stock-input]');if(input){input.value=S.setInventory(input.dataset.stockInput,input.value);updateStats()}});
$('[data-import-file]').addEventListener('change',e=>{const [file]=e.target.files;if(file)importWorkspace(file);e.target.value=''});
const search=$('[data-library-search]');search.addEventListener('input',()=>filterLibrary($('[data-filter].active')?.dataset.filter||'all'));$('[data-clear-search]').addEventListener('click',()=>{search.value='';filterLibrary($('[data-filter].active')?.dataset.filter||'all');search.focus()});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();search.focus();search.select()}});
window.addEventListener('tf:state',()=>{syncFavorites();renderFavorites()});
})();
