(()=>{
'use strict';
const pedals=[
 ['fuzz-face','Fuzz Face','Fuzz','PNP-Germanium · Cleanup über Guitar Volume','asym'],['tube-screamer','TS808 · True-Bypass-Effektkern','Overdrive','4558 Soft-Clipping · Mittenfokus','soft'],['rat','ProCo RAT · Type B Rev. 7-81','Distortion','LM308 · Hard Clip · Filter','hard'],['big-muff','Big Muff Pi · American V3 Referenz','Fuzz / Sustain','4 Transistorstufen · Doppel-Clipping','muff'],['compressor','MXR Dyna Comp · CA3080','Compressor','CA3080 OTA · Envelope Control','comp'],['phase90','MXR Phase 90 · Script Logo','Phaser','4 Allpass-Stufen · gematchte JFETs','phase'],['chorus','BOSS CE-2 · MN3007/MN3101','Chorus','MN3007 BBD · MN3101 Clock','chor'],['pt2399','PT2399 Delay · Synthrotek v0.4','Delay','CMOS Echo · Feedback / Mix · BOM-Abgleich offen','delay'],['distortion-plus','MXR Distortion+','Distortion','LM741 · Germanium Hard Clip','hard'],['vox-v847','Vox V847 Wah','Wah-Wah','500mH LC-Resonanz · 100k Sweep','phase'],['rangemaster','Dallas Rangemaster','Treble Booster','OC44 PNP · Vintage Boost','soft'],['tone-bender-mkii','Tone Bender Mark II Professional · PNP Germanium','Fuzz','GGG PNP-Germanium-Replica','muff'],['green-ringer','Dan Armstrong Green Ringer','Octave Up','Analoger Vollweggleichrichter','asym'],['ea-tremolo','Improved EA Tremolo','Tremolo','JFET Gain Control · LFO','phase'],['boss-ds1','BOSS DS-1 · Revision auswählen','Distortion','Service- und DIY-Referenzen · Revision offen','hard'],['sd1','BOSS SD-1 · Revision auswählen','Overdrive','Service- und True-Bypass-Referenz','soft'],['micro-amp','MXR Micro Amp · TL061','Clean Boost','Klassische M-133 TL061-Referenz','comp'],['orange-squeezer','Dan Armstrong Orange Squeezer','Compressor','JFET-Kompression · GGG-Referenz','comp'],['noise-gate','No-Noise Gate · JFET','Noise Gate','PCB Guitar Mania v1.2 · BOM-Abgleich offen','comp'],['envelope-filter','Minima Resonant Filter · Mu-Tron Micro V','Auto-Wah','Aion LM13700-Adaption','phase'],['belton-reverb','Sproing Reverb · BTDR-2H','Reverb','PedalPCB · BTDR-2H(L)','chor'],['aby-buffered','Buffered ABY · Dual IC Buffer','Utility','GGG Dual-IC-Buffer · keine galvanische Isolation','comp'],['volume-passive','Passive Volume · 250K','Utility','Passiver Audio-Spannungsteiler','comp'],['sample-trigger','Adafruit Audio FX Sample Trigger','Sample / Trigger','11 GPIO-Trigger · Audio-FX-Board','delay'],['talkbox','Heil HT-1 Style Talk Box · External Amp','Performance-Effekt','Speaker-Level · Kompressionstreiber · Schlauch','chor']
];
const amps=[['5f1','Fender Champ 5F1','Tube amp','5 W · Single-Ended · 6V6'],['5e3','Fender Deluxe 5E3','Tube amp','ca. 12–15 W · 2×6V6'],['jcm800-2204','Marshall JCM800 2204 · 50 W','Tube amp','50 W · EL34 · Master Volume'],['ac15','Vox AC15 No.3 · OA/031','Tube amp','Jennings 1960 · ca. 15 W · EL84'],['b15n','Ampeg B-15N · Revision auswählen','Bass amp','Vintage B-15N-Familie · Revision offen'],['ruby','Runoffgroove Ruby · LM386','Mini amp','Solid-State · Übungsamp'],['tda7294','TDA7294 · ST Datasheet Application','Power amp','Solid-State · ca. 50–70 W']];
const wiring=[['strat-5way','Strat 5-Way','SSS Wiring','3 Single Coils · 5 Wege'],['tele-3way','Tele 3-Way','SS Wiring','Bridge / beide / Neck'],['les-paul','Les Paul 50s/Modern','HH Wiring','2 Volume + 2 Tone'],['coil-split','Coil Split','Humbucker Mod','Seymour-Duncan-Farbcode · Spule abschalten'],['series-parallel','Series / Parallel','Humbucker Mod','Seriell oder parallel'],['treble-bleed','Treble Bleed','Volume Mod','Höhen beim Abregeln erhalten'],['blower-switch','Blower Switch','Direct Bypass','Pickup direkt zum Ausgang'],['hss-autosplit','HSS Auto-Split','HSS Wiring','Bridge HB splittet in Position 2'],['hsh-superswitch','HSH Super Switch','HSH Wiring','4-poliger 5-Way Super Switch'],['phase-reverse','Pickup Phase Reverse','Pickup Mod','DPDT Out-of-Phase'],['kill-switch','Momentary Kill Switch','Performance Mod','Signal kurzzeitig auf Masse'],['nashville-tele','Nashville Tele 5-Way','SSS Tele','Bridge + Middle + Neck']];
const pickups=[['strat-pickup','50s / Early-60s Strat Single Coil','Single Coil','7,900–8,350 turns · 42 AWG · Alnico 5'],['tele-bridge-pickup','50s Tele Bridge Pickup','Single Coil','8,000–9,200 turns · 42 AWG · Alnico 5'],['p90','Vintage P-90 · 10,000 turns','Single Coil','42 AWG · zwei Alnico-Bar-Magnete'],['paf','PAF-style Humbucker · 5,000 turns/coil','Humbucker','2× 5,000–5,050 turns · 42 AWG'],['p-bass','50s/60s Precision Bass Split Coil','Split Coil','2× ~10,000 turns · RWRP'],['j-bass','50s/60s Jazz Bass Set','Single Coil Bass','~9,500 turns je Pickup · RWRP-Paar']];
const instruments=[['theremin','Open.Theremin V3 · Arduino Shield','Elektronisches Instrument','KiCad · BOM · Gerber · Open Source'],['stylophone','1968 Dubreq Stylophone · Reconstruction','Elektronisches Instrument','KiCad + OpenSCAD · Reverse Engineering'],['keyboard','mechmidi1 · RP2040 MIDI Controller','Elektronisches Instrument','20 Keys · Prototype · mechanische Revision offen']];
const bodies=[['e-guitar','’62 Stratocaster Body · 1:1 Plan','Holzbau','1:1 PDF · cavities · neck pocket · cross-sections'],['e-bass','1957 Precision Bass · Full-Scale DXF/PDF','Holzbau','1:1 DXF/PDF · paid reference · Fender crosscheck'],['e-violin','OpenFab F-F-Fiddle · Electric Violin','Holzbau','Full-size FFF electric violin · STL/CAD · piezo']];
const components=[
 ['resistors','Widerstände','Metallfilm 1/4 W: E12/E24; 100 Ω–10 MΩ'],['capacitors','Kondensatoren','Film 1 nF–1 µF; Elkos 1–1000 µF; Keramik/C0G für HF'],['diodes','Dioden','1N4148/1N914, 1N5817, 1N400x, Zener 5.1 V, Germanium, LEDs'],['transistors','Transistoren / JFETs','2N3904/06, 2N5088/89, BC550C, J201, 2N5457/58, 2N5952'],['opamps','OpAmps / ICs','TL072/TL074, JRC4558, NE5532, LM358, LM741, LM308/OP07, PT2399, LM386'],['bbd','BBD / Clock','MN3007/MN3207, MN3101/MN3102 – Pinout und Versorgung prüfen'],['pots','Potis / Trimmer','1 kΩ–1 MΩ; linear/log/reverse-log; 9/16 mm; Trimmpotis'],['switches','Schalter','3PDT Fußschalter, DPDT Toggle, Push/Pull, Rotary, Blade/Super Switch, Momenttaster'],['connectors','Buchsen / Verbinder','6,3-mm Mono/Stereo, DC 2,1 mm, JST, Header, Schraubklemmen'],['pickup-material','Pickup-Material','42/43 AWG Magnetdraht, Alnico 2/3/5, Pole Pieces, Baseplates, Flatwork'],['amp-parts','Amp-Bauteile','Röhrenfassungen, Turret/Eyelet, Netz-/Ausgangstrafo, Sicherungshalter, Hochvolt-Elkos'],['mechanics','Mechanik','1590B/125B Gehäuse, Wah-Gehäuse, Knöpfe, Abstandshalter, Schrauben, abgeschirmter Draht'],['workshop','Mess-/Werkstattteile','IC-Sockel, Testpunkte, Sicherungen, Schrumpfschlauch, Lötösen, Audio-Probe, Testkabel']
];
const categories=[
 {id:'pedals',type:'pedal',label:'Pedale',eyebrow:'Effects',items:pedals,icon:'pedal'},
 {id:'amps',type:'amp',label:'Verstärker',eyebrow:'Amplification',items:amps,icon:'amp'},
 {id:'wiring',type:'wiring',label:'Gitarrenschaltungen',eyebrow:'Instrument wiring',items:wiring,icon:'wiring'},
 {id:'pickups',type:'pickup',label:'Tonabnehmer',eyebrow:'Pickup workshop',items:pickups,icon:'pickup'},
 {id:'instruments',type:'instrument',label:'Instrumente',eyebrow:'Build lab',items:instruments,icon:'instrument'},
 {id:'bodies',type:'body',label:'Korpus & Holzbau',eyebrow:'Templates',items:bodies,icon:'body'}
];
const all=categories.flatMap(c=>c.items.map(x=>({id:x[0],name:x[1],kind:x[2],meta:x[3],wave:x[4]||'comp',type:c.type,category:c.id,key:`${c.type}:${x[0]}`})));
window.ToneForgeLibrary={categories,components,all};
})();
