(()=>{
'use strict';
const pedals=[
 ['fuzz-face','Fuzz Face','Fuzz','PNP-Germanium · Cleanup über Guitar Volume','asym'],['tube-screamer','Tube Screamer','Overdrive','4558 Soft-Clipping · Mittenfokus','soft'],['rat','RAT-artig','Distortion','LM308 · Hard Clip · Filter','hard'],['big-muff','Big Muff Pi V3','Fuzz / Sustain','4 Transistorstufen · Doppel-Clipping','muff'],['compressor','Dyna Comp','Compressor','CA3080 OTA · Envelope Control','comp'],['phase90','Phase 90 Script','Phaser','4 Allpass-Stufen · gematchte JFETs','phase'],['chorus','CE-2','Chorus','MN3007 BBD · MN3101 Clock','chor'],['pt2399','PT2399 Delay','Delay','CMOS Echo · Feedback / Mix','delay'],['distortion-plus','MXR Distortion+','Distortion','LM741 · Germanium Hard Clip','hard'],['vox-v847','Vox V847 Wah','Wah-Wah','500mH LC-Resonanz · 100k Sweep','phase'],['rangemaster','Dallas Rangemaster','Treble Booster','OC44 PNP · Vintage Boost','soft'],['tone-bender-mkii','Tone Bender MkII','Fuzz','3× PNP Germanium','muff'],['green-ringer','Green Ringer','Octave Up','Analoger Vollweggleichrichter','asym'],['ea-tremolo','Improved EA Tremolo','Tremolo','JFET Gain Control · LFO','phase'],['boss-ds1','Boss DS-1-artig','Distortion','Transistor Boost · Hard Clip · Midscoop','hard'],['sd1','Boss SD-1-artig','Overdrive','Asymmetrisches Soft-Clipping','soft'],['micro-amp','MXR Micro Amp-artig','Clean Boost','OpAmp Variable Gain','comp'],['orange-squeezer','Orange Squeezer','Compressor','JFET-Kompression','comp'],['noise-gate','JFET Noise Gate','Noise Gate','Envelope · Threshold · Mute','comp'],['envelope-filter','Envelope Filter','Auto-Wah','Anschlaggesteuerter Filter','phase'],['belton-reverb','Belton Brick Reverb','Reverb','BTDR Modul · Dry/Wet','chor'],['aby-buffered','Buffered ABY','Utility','Split · Phase · optional Isolation','comp'],['volume-passive','Passive Volume','Utility','Passiver Audio-Spannungsteiler','comp'],['sample-trigger','Programmable Sample Trigger','Troll / Sample','Eigene Samples · Trigger · Dry/Wet','delay'],['talkbox','Talkbox','Performance-Effekt','Verstärker · Kompressionstreiber · Schlauch','chor']
];
const amps=[['5f1','5F1 Champ','Tube amp','5 W · Single-Ended · 6V6'],['5e3','5E3 Deluxe','Tube amp','ca. 12–15 W · 2×6V6'],['jcm800-2204','JCM800 2204-artig','Tube amp','50 W · EL34 · Master Volume'],['ac15','AC15-artig','Tube amp','ca. 15 W · EL84'],['b15n','B-15N-artig','Bass amp','Bass · Röhrenamp'],['ruby','Ruby / LM386','Mini amp','Solid-State · Übungsamp'],['tda7294','TDA7294 Power Amp','Power amp','Solid-State · ca. 50–70 W']];
const wiring=[['strat-5way','Strat 5-Way','SSS Wiring','3 Single Coils · 5 Wege'],['tele-3way','Tele 3-Way','SS Wiring','Bridge / beide / Neck'],['les-paul','Les Paul 50s/Modern','HH Wiring','2 Volume + 2 Tone'],['coil-split','Coil Split','Humbucker Mod','Spule per Push/Pull abschalten'],['series-parallel','Series / Parallel','Humbucker Mod','Seriell oder parallel'],['treble-bleed','Treble Bleed','Volume Mod','Höhen beim Abregeln erhalten'],['blower-switch','Blower Switch','Direct Bypass','Pickup direkt zum Ausgang'],['hss-autosplit','HSS Auto-Split','HSS Wiring','Bridge HB splittet in Position 2'],['hsh-superswitch','HSH Super Switch','HSH Wiring','4-poliger 5-Way Super Switch'],['phase-reverse','Pickup Phase Reverse','Pickup Mod','DPDT Out-of-Phase'],['kill-switch','Momentary Kill Switch','Performance Mod','Signal kurzzeitig auf Masse'],['nashville-tele','Nashville Tele 5-Way','SSS Tele','Bridge + Middle + Neck']];
const pickups=[['strat-pickup','Strat Single Coil','Single Coil','42 AWG · Alnico Rods'],['tele-bridge-pickup','Tele Bridge','Single Coil','42/43 AWG · Baseplate'],['p90','P-90','Single Coil','42 AWG · 2 Bar Magnets'],['paf','PAF-artiger Humbucker','Humbucker','2 Spulen · Bar Magnet'],['p-bass','Precision Bass','Split Coil','Hum-cancelling Bass'],['j-bass','Jazz Bass','Single Coil Bass','42/43 AWG · lange Spule']];
const instruments=[['theremin','Theremin','Elektronisches Instrument','Berührungslos · Heterodyn-Prinzip'],['stylophone','Stylophone-artiger Synth','Elektronisches Instrument','Stift · Widerstandsleiter · Oszillator'],['keyboard','Modulares DIY-Keyboard','Elektronisches Instrument','RP2040/ESP32 · Matrix · DAC']];
const bodies=[['e-guitar','E-Gitarren-Korpus','Holzbau','Mensur · Fräsungen · Elektronikfach'],['e-bass','E-Bass-Korpus','Holzbau','Mensur · Balance · Brückenposition'],['e-violin','E-Violine / E-Geige','Holzbau','Ergonomie · Piezo · Halswinkel']];
const components=[
 ['resistors','Widerstände','Metallfilm 1/4 W: E12/E24; 100 Ω–10 MΩ'],['capacitors','Kondensatoren','Film 1 nF–1 µF; Elkos 1–1000 µF; Keramik/C0G für HF'],['diodes','Dioden','1N4148/1N914, 1N5817, 1N400x, Zener 5.1 V, Germanium, LEDs'],['transistors','Transistoren / JFETs','2N3904/06, 2N5088/89, BC550C, J201, 2N5457/58, 2N5952'],['opamps','OpAmps / ICs','TL072/TL074, JRC4558, NE5532, LM358, LM741, LM308/OP07, PT2399, LM386'],['bbd','BBD / Clock','MN3007/MN3207, MN3101/MN3102 – Pinout und Versorgung prüfen'],['pots','Potis / Trimmer','1 kΩ–1 MΩ; linear/log/reverse-log; 9/16 mm; Trimmpotis'],['switches','Schalter','3PDT Fußschalter, DPDT Toggle, Push/Pull, Rotary, Blade/Super Switch, Momenttaster'],['connectors','Buchsen / Verbinder','6,3-mm Mono/Stereo, DC 2,1 mm, JST, Header, Schraubklemmen'],['pickup-material','Pickup-Material','42/43 AWG Magnetdraht, Alnico 2/3/5, Pole Pieces, Baseplates, Flatwork'],['amp-parts','Amp-Bauteile','Röhrenfassungen, Turret/Eyelet, Netz-/Ausgangstrafo, Sicherungshalter, Hochvolt-Elkos'],['mechanics','Mechanik','1590B/125B Gehäuse, Wah-Gehäuse, Knöpfe, Abstandshalter, Schrauben, abgeschirmter Draht'],['workshop','Mess-/Werkstattteile','IC-Sockel, Testpunkte, Sicherungen, Schrumpfschlauch, Lötösen, Audio-Probe, Testkabel']
];
const categories=[
 {id:'pedals',type:'pedal',label:'Pedale',eyebrow:'Effects',items:pedals,icon:'pedal'},
 {id:'amps',type:'amp',label:'Verstärker',eyebrow:'Amplification',items:amps,icon:'amp'},
 {id:'wiring',type:'wiring',label:'Gitarrenschaltungen',eyebrow:'Instrument wiring',items:wiring,icon:'wiring'},
 {id:'pickups',type:'pickup',label:'Tonabnehmer',eyebrow:'Pickup workshop',items:pickups,icon:'pickup'},
 {id:'instruments',type:'instrument',label:'Instrumente',eyebrow:'Build lab',items:instruments,icon:'instrument'},
 {id:'bodies',type:'body',label:'Korpus & Holzbau',eyebrow:'Templates',items:bodies,icon:'body'}
];
const all=categories.flatMap(c=>c.items.map(x=>({id:x[0],name:x[1],kind:x[2],meta:x[3],wave:x[4]||'comp',type:c.type,category:c.id,key:`${c.type}:${x[0]}`})));
window.ToneForgeLibrary={categories,components,all};
})();
