(()=>{
'use strict';
window.ToneForgeMedia={
  'pedal:fuzz-face':{photo:'https://thumbs.static-thomann.de/thumb//bdbmagic/pics/prod/309741.jpg',source:'https://www.thomann.de/de/dunlop_germanium_fuzz_face_mini_red.htm',credit:'Thomann · Dunlop Germanium Fuzz Face Mini'},
  'pedal:tube-screamer':{photo:'https://thumbs.static-thomann.de/thumb/padthumb600x600/pics/bdb/_17/170627/10631407_800.jpg',source:'https://www.thomannmusic.com/ibanez_ts808.htm',credit:'Thomann · Ibanez TS808'},
  'pedal:rat':{photo:'https://tonearchitect.app/proco-rat2-photo.jpg',source:'https://tonearchitect.app/',credit:'Tone Architect · ProCo RAT 2'},
  'pedal:big-muff':{photo:'https://cdn.shopify.com/s/files/1/0618/9039/6265/files/electro-harmonix-big-muff-usa-music-planet-new-zealand-6712459_400x400.jpg?v=1752168771',source:'https://www.musicplanet.co.nz/products/electro-harmonix-usa-big-muff-pi-distortion-sustainer-ehx-bm',credit:'Music Planet · Electro-Harmonix Big Muff Pi'},
  'pedal:compressor':{photo:'https://thumbs.static-thomann.de/thumb//bdbmagic/pics/prod/129745.jpg',source:'https://www.thomann.de/de/mxr_dynacomp.htm',credit:'Thomann · MXR Dyna Comp'},
  'pedal:phase90':{photo:'https://cdn11.bigcommerce.com/s-n26aknlnlm/images/stencil/500x659/products/691/6739/16101003001.MAIN__44494.1663874799.jpg?c=2',source:'https://www.jimdunlop.com/mxr-74-vintage-phase-90/',credit:'Jim Dunlop · MXR ’74 Vintage Phase 90'},
  'pedal:chorus':{photo:'https://monteallums.com/wordpress/wp-content/uploads/2023/09/CE-2_Web.jpg',source:'https://monteallums.com/wordpress/product/boss-ce-2-ce-2b-diy-pedal-mod-kits/',credit:'Monte Allums · Boss CE-2 reference'},
  'pedal:pt2399':{photo:'https://store.synthrotek.com/assets/images/PT2399_Dev_Delay_Complete_01.jpg',source:'https://store.synthrotek.com/PT2399_Dev_Delay_Kit',credit:'Synthrotek · PT2399 Dev Delay Kit'},
  'pedal:distortion-plus':{photo:'https://www.truetonemusic.com/cdn/shop/files/1-Img5904_700x700.jpg?v=1713816743',source:'https://www.truetonemusic.com/products/used-mxr-distortion-plus-pedal-with-box',credit:'Truetone Music · MXR Distortion+'},
  'pedal:vox-v847':{photo:'https://cdn.sanity.io/images/5skqgt41/production/2a6d029d229e836ab8fe8f7ae8ee86e5f8b51d4b-1000x1000.jpg?auto=format',source:'https://www.mannys.com.au/products/vox-v847-wah-pedal',credit:'Mannys · Vox V847'},
  'pedal:rangemaster':{photo:'https://store.generalguitargadgets.com/cdn/shop/products/geb_pcb_c75abfb9-dbbd-4a1c-b54b-88dc9d4198b5_300x300.jpg?v=1591108981',source:'https://store.generalguitargadgets.com/products/dallas-arbiter%E2%84%A2-rangmaster%E2%84%A2-replica-rts-pcb',credit:'General Guitar Gadgets · Rangemaster RTS PCB'},
  'pedal:tone-bender-mkii':{photo:'https://store.generalguitargadgets.com/cdn/shop/products/tb2_pcb_300x300.jpg?v=1591120803',source:'https://store.generalguitargadgets.com/products/colorsound%E2%84%A2-tonebender%E2%84%A2-mark-ii-professional-replica-rts-pcb',credit:'General Guitar Gadgets · Tone Bender MkII RTS PCB'},
  'pedal:green-ringer':{photo:'https://store.generalguitargadgets.com/cdn/shop/products/gro_pcb_300x300.jpg?v=1591195000',source:'https://store.generalguitargadgets.com/products/dan-armstrong%E2%84%A2-green-ringer%E2%84%A2-replica-rts-pcb',credit:'General Guitar Gadgets · Green Ringer RTS PCB'},
  'pedal:ea-tremolo':{photo:'https://store.generalguitargadgets.com/cdn/shop/products/eat_kit_300x300.jpg?v=1591736489',source:'https://store.generalguitargadgets.com/products/improved-ea-tremolo-complete-kit',credit:'General Guitar Gadgets · Improved EA Tremolo Kit'},
  'pedal:boss-ds1':{photo:'https://static.roland.com/products/ds-1/images/ds-1_top.png',source:'https://www.boss.info/GLOBAL/products/ds-1/',credit:'BOSS · DS-1 Distortion'},
  'pedal:sd1':{photo:'https://static.roland.com/products/sd-1-4a/images/sd-1_top.png',source:'https://www.boss.info/de/products/sd-1/',credit:'BOSS · SD-1 Super OverDrive'},
  'pedal:micro-amp':{photo:'https://cdn11.bigcommerce.com/s-n26aknlnlm/images/stencil/1280x1280/products/2064/10730/M133.MAIN__39765.1701991028.jpg?c=2',source:'https://www.jimdunlop.com/mxr-micro-amp-parts/',credit:'Jim Dunlop · MXR Micro Amp'},
  'pedal:orange-squeezer':{photo:'https://store.generalguitargadgets.com/cdn/shop/products/osq_pcb_pic_l_300x300.jpg?v=1591117695',source:'https://store.generalguitargadgets.com/products/dan-armstrong%E2%84%A2-orange-squeezer%E2%84%A2-replica-rts-pcb',credit:'General Guitar Gadgets · Orange Squeezer RTS PCB'},
  'pedal:noise-gate':{photo:'https://rvb-img.reverb.com/image/upload/s--UWT9V3c4--/t_card-square/v1614120788/lmws3yzczzuwhfdijttk.jpg',source:'https://reverb.com/p/mxr-mx-106-noise-gate-line-driver',credit:'Reverb product gallery · MXR MX-106 Noise Gate Line Driver'},
  'pedal:envelope-filter':{photo:'https://aionfx.com/app/files/projects/minima-resonant-filter-pcb.png',source:'https://aionfx.com/project/minima-resonant-filter/',credit:'Aion FX · Minima Resonant Filter PCB'},
  'pedal:belton-reverb':{photo:'https://www.pedalpcb.com/wp-content/uploads/2022/05/Sproing-510x600.jpg',source:'https://www.pedalpcb.com/product/pcb459/',credit:'PedalPCB · Sproing Reverb PCB'},
  'pedal:aby-buffered':{photo:'https://store.generalguitargadgets.com/cdn/shop/products/ic2buf_pcb_300x300.jpg?v=1591045182',source:'https://store.generalguitargadgets.com/products/dual-ic-buffer-rts-pcb',credit:'General Guitar Gadgets · Dual IC Buffer RTS PCB'},
  'pedal:volume-passive':{photo:'https://s3.us-west-2.amazonaws.com/static.ernieball.com/website/images/products/image_front/large/P06180.png',source:'https://www.ernieball.com/guitar-accessories/pedals/volume-pedals',credit:'Ernie Ball · VP Jr 250K P06180'},
  'pedal:sample-trigger':{photo:'https://cdn-shop.adafruit.com/970x728/2220-06.jpg',source:'https://www.adafruit.com/product/2220',credit:'Adafruit · Audio FX Sound Board 16MB'},
  'pedal:talkbox':{photo:'https://cdn11.bigcommerce.com/s-n26aknlnlm/images/stencil/500x659/products/656/6580/11501000001.MAIN__54495.1663874797.jpg?c=2',source:'https://www.jimdunlop.com/heil-talk-box/',credit:'Jim Dunlop / Heil · HT-1 Talk Box'}
};
})();
