(()=>{
'use strict';
window.GBE_SCHEMATIC_SOURCES={
 'pedal:fuzz-face':[{label:'Dallas-Arbiter Fuzz Face',standard:'ANSI',revision:'klassische PNP-/NPN-Referenztopologie',image:'https://electronicscheme.net/wp-content/uploads/2011/03/fuzz-face-circuit-diagram.jpg',source:'https://electronicscheme.net/dallas-arbiter-fuzz-face/',publisher:'Electronic Schematic Diagram',trust:'reference',review:'source-found',note:'Referenzplan. Exakte Transistorvariante, Polarität und Revision vor Aufbau gegen weitere Quellen prüfen.'}],
 'pedal:distortion-plus':[{label:'MXR Distortion Plus · LM741',standard:'ANSI',revision:'klassischer Distortion+-Effektkern',image:'https://barbarach.com/wp-content/uploads/2022/01/MXRDistPlus_LM741_Schematic.png',source:'https://barbarach.com/mxr-distortion-plus-on-breadboard/',publisher:'Barbarach BC',trust:'established-diy',review:'source-found',note:'Noch nicht als Original-Serviceunterlage verifiziert.'}],
 'pedal:rat':[{label:'ProCo RAT · Type B',standard:'ANSI',revision:'Type B · Rev. 7-81',image:'https://www.generalguitargadgets.com/wp-content/uploads/ratb.gif',source:'https://www.generalguitargadgets.com/effects-projects/distortion/rat/',publisher:'General Guitar Gadgets',trust:'established-diy',review:'crosschecked',note:'Revision ist ausdrücklich Type B Rev. 7-81; nicht mit späteren RAT2-/Turbo-RAT-Varianten vermischen.'}],
 'pedal:tube-screamer':[{label:'Ibanez TS-808 Service-Schaltplan',standard:'ANSI',revision:'TS-808 · historische Service-Unterlage',image:'https://www.tonehome.de/app/download/8039226/Ibanez_TS808_Schematics.jpg',source:'https://www.tonehome.de/ibanez/0-series-ts-808/ts-808-tube-scr/',publisher:'ToneHome · Ibanez-Serviceunterlage',trust:'service-copy',review:'source-found',note:'Originaler TS808-Effektkern; elektronisches JFET-Bypass-System vom True-Bypass-Mod getrennt behandeln.'}],
 'wiring:treble-bleed':[{label:'Treble-Bleed · Kondensator und Parallelwiderstand',standard:'WIRING',revision:'Volume-Poti · parallele RC-Variante',image:'https://www.guitar-mod.com/images/treble_bleed/treble_retention_w_res.jpg',source:'https://www.guitar-mod.com/rg_diag_treble_bleed.html',publisher:'Rothstein Guitars',trust:'established-diy',review:'crosschecked'}],
 'wiring:kill-switch':[{label:'Momentary Kill Switch / Output Mute',standard:'WIRING',revision:'Normally-open-Taster gegen Masse',image:'https://cdn11.bigcommerce.com/s-fxdzp2uudp/images/stencil/1280x1280/products/2525/5390/WIRING_MOD_SW001__23857.1471907091.jpg?c=2',source:'https://guitarelectronics.com/guitar-kill-switch-output-mute-switch/',publisher:'GuitarElectronics.com',trust:'established-diy',review:'source-found'}],
 'wiring:phase-reverse':[{label:'Pickup In Phase / Reverse Phase',standard:'WIRING',revision:'DPDT On/On · Pickup Hot/Cold umschalten',image:'https://cdn11.bigcommerce.com/s-fxdzp2uudp/images/stencil/1280x1280/products/2522/5406/In_Phase_Reverse_Phase__40362.1471991208.jpg',source:'https://guitarelectronics.com/guitar-wiring-resources/guitar-pickup-control-wiring-mods/',publisher:'GuitarElectronics.com',trust:'established-diy',review:'source-found'}],
 'wiring:coil-split':[{label:'Humbucker Coil Split',standard:'WIRING',revision:'Push/Pull · Hersteller-Farbcode erforderlich',image:'',source:'https://www.seymourduncan.com/resources/pickup/wiring-diagrams',publisher:'Seymour Duncan',trust:'manufacturer',review:'source-found',note:'Kein generisches Farbschema vortäuschen: Leiterfarben und Serienverbindung müssen zum konkreten Pickup-Hersteller passen.'}]
};
})();
