(()=>{
'use strict';
const stages=[...document.querySelectorAll('.plan-stage')];if(!stages.length)return;
const project=stages[0].dataset.project||'unknown',storageKey=`gbe-marker-v2:${project}`;
const colors={red:'#ff4d5a',green:'#31c979',blue:'#3d8fff'},installed=new Set();let mode='select',active=null,marks=[];
try{marks=JSON.parse(localStorage.getItem(storageKey)||'[]');if(!Array.isArray(marks))marks=[]}catch{marks=[]}
const save=()=>localStorage.setItem(storageKey,JSON.stringify(marks));
const toolbar=document.createElement('div');toolbar.className='marker-tools';toolbar.setAttribute('role','toolbar');toolbar.setAttribute('aria-label','Schaltplan markieren');toolbar.innerHTML='<span>Textmarker</span><button type="button" data-marker="select" class="active">Auswählen</button><button type="button" data-marker="red"><i class="marker-dot red"></i>Rot</button><button type="button" data-marker="green"><i class="marker-dot green"></i>Grün</button><button type="button" data-marker="blue"><i class="marker-dot blue"></i>Blau</button><button type="button" data-marker-action="undo">↶ Rückgängig</button><button type="button" data-marker-action="clear">Markierungen löschen</button>';
(document.querySelector('.schem')||document.querySelector('.source-plan-list'))?.insertAdjacentElement('beforebegin',toolbar);
const point=(stage,event)=>{const rect=stage.getBoundingClientRect();if(!rect.width||!rect.height)return null;return{x:Math.max(0,Math.min(1000,(event.clientX-rect.left)/rect.width*1000)),y:Math.max(0,Math.min(1000,(event.clientY-rect.top)/rect.height*1000))}};
const render=stage=>{const surface=stage.querySelector('.plan-annotation-surface');if(!surface)return;surface.replaceChildren();const index=Number(stage.dataset.planIndex||0);[...marks,active].filter(mark=>mark&&mark.plan===index&&mark.points?.length).forEach(mark=>{const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',mark.points.map((p,i)=>`${i?'L':'M'}${p.x.toFixed(1)} ${p.y.toFixed(1)}`).join(' '));path.setAttribute('stroke',mark.color);path.setAttribute('class','marker-stroke');surface.append(path)})};
const renderAll=()=>{for(const stage of [...installed])stage.isConnected?render(stage):installed.delete(stage)};
const finish=event=>{if(!active)return;event?.preventDefault();event?.stopImmediatePropagation();if(active.points.length>1){marks.push(active);save()}active=null;renderAll()};
const install=stage=>{if(installed.has(stage))return;installed.add(stage);render(stage);stage.addEventListener('pointerdown',event=>{if(!colors[mode])return;event.preventDefault();event.stopImmediatePropagation();const p=point(stage,event);if(!p)return;active={plan:Number(stage.dataset.planIndex||0),color:colors[mode],points:[p]};stage.setPointerCapture?.(event.pointerId);renderAll()},true);stage.addEventListener('pointermove',event=>{if(!active)return;event.preventDefault();event.stopImmediatePropagation();const p=point(stage,event),last=active.points.at(-1);if(p&&(!last||Math.hypot(p.x-last.x,p.y-last.y)>2)){active.points.push(p);renderAll()}},true);stage.addEventListener('pointerup',finish,true);stage.addEventListener('pointercancel',finish,true);stage.addEventListener('click',event=>{if(colors[mode]){event.preventDefault();event.stopImmediatePropagation()}},true)};
toolbar.addEventListener('click',event=>{const selected=event.target.closest('[data-marker]')?.dataset.marker,action=event.target.closest('[data-marker-action]')?.dataset.markerAction;if(selected){mode=selected;document.documentElement.classList.toggle('marker-active',Boolean(colors[mode]));toolbar.querySelectorAll('[data-marker]').forEach(button=>button.classList.toggle('active',button.dataset.marker===mode))}if(action==='undo'&&marks.length){marks.pop();save();renderAll()}if(action==='clear'&&marks.length){marks=[];save();renderAll()}});
stages.forEach(install);new MutationObserver(records=>records.forEach(record=>record.addedNodes.forEach(node=>{if(node.nodeType!==1)return;if(node.matches?.('.plan-stage'))install(node);node.querySelectorAll?.('.plan-stage').forEach(install)}))).observe(document.body,{childList:true,subtree:true});
})();