(()=>{
'use strict';
window.GBE_SCHEMATIC_SOURCES={
 'pedal:fuzz-face':[{label:'Dallas-Arbiter Fuzz Face',standard:'ANSI',revision:'klassische Referenztopologie',image:'https://electronicscheme.net/wp-content/uploads/2011/03/fuzz-face-circuit-diagram.jpg',source:'https://electronicscheme.net/dallas-arbiter-fuzz-face/',publisher:'Electronic Schematic Diagram',trust:'reference',review:'source-found',note:'Referenzplan. PNP/NPN-Variante, Massepolarität und Transistor-Pinout vor dem Aufbau konkret festlegen.'}],
 'pedal:tube-screamer':[{label:'Ibanez TS-808 Service-Schaltplan',standard:'ANSI',revision:'TS-808 · historische Service-Unterlage',image:'https://www.tonehome.de/app/download/8039226/Ibanez_TS808_Schematics.jpg',source:'https://www.tonehome.de/ibanez/0-series-ts-808/ts-808-tube-scr/',publisher:'ToneHome · Ibanez-Serviceunterlage',trust:'service-copy',review:'source-found',note:'Originalen JFET-Bypass des TS808 nicht mit einem True-Bypass-Umbau vermischen.'}],
 'pedal:rat':[{label:'ProCo RAT · Type B',standard:'ANSI',revision:'Type B · Rev. 7-81',image:'https://www.generalguitargadgets.com/wp-content/uploads/ratb.gif',source:'https://www.generalguitargadgets.com/effects-projects/distortion/rat/',publisher:'General Guitar Gadgets',trust:'established-diy',review:'crosschecked',note:'Explizit Type B Rev. 7-81; nicht als universeller RAT2-/Turbo-RAT-Plan behandeln.'}],
 'pedal:big-muff':[{label:'Electro-Harmonix Big Muff Pi · V3 Circuit Guide',standard:'ANSI',revision:'V3-Familie · konkrete Untervariante vor Aufbau wählen',image:'',source:'https://www.kitrae.net/music/Images_Secret_Music_Page/BIG%20MUFF%20CIRCUIT%20GUIDE.pdf',publisher:'Kit Rae · Big Muff Page',trust:'established-diy',review:'source-found',note:'Die V3-Familie besitzt mehrere Schaltungsvarianten. ToneForge behandelt diesen Eintrag noch nicht als eindeutigen Build-Plan, bis eine konkrete V3-Revision festgelegt ist.'}],
 'pedal:compressor':[{label:'MXR Dyna Comp · CA3080',standard:'ANSI',revision:'klassische CA3080-Schaltung',image:'https://www.electrosmash.com/images/tech/mxr-dyna-comp/mxr-dyna-comp-schematic-parts.png',source:'https://www.electrosmash.com/mxr-dyna-comp-analysis',publisher:'ElectroSmash',trust:'established-diy',review:'crosschecked',note:'Schaltplan und BOM sind gemeinsam dokumentiert; konkrete historische PCB-Revision vor 1:1-Replikation zusätzlich prüfen.'}],
 'pedal:phase90':[{label:'MXR Phase 90 · Script Logo',standard:'ANSI',revision:'erste Script-Logo-Topologie',image:'https://www.electrosmash.com/images/tech/phase-90/mxr-phase-90-script-logo-schematic-parts.png',source:'https://electrosmash.com/mxr-phase90',publisher:'ElectroSmash',trust:'established-diy',review:'crosschecked',note:'Script-Logo-Schaltung. Spätere Block-Logo-Versionen und R28-Feedback-Varianten sind davon zu trennen; JFETs müssen passend gematcht werden.'}],
 'pedal:chorus':[{label:'Boss CE-2 · MN3007 / MN3101',standard:'ANSI',revision:'klassische CE-2 BBD-Topologie',image:'https://www.electrosmash.com/images/tech/ce-2/boss-ce-2-schematic-parts.png',source:'https://www.electrosmash.com/boss-ce-2-analysis',publisher:'ElectroSmash',trust:'established-diy',review:'crosschecked',note:'CE-2 mit MN3007/MN3101 und originalem JFET-Switching. ACA-/PSA-Versorgungsrevisionen gesondert beachten.'}],
 'pedal:pt2399':[{label:'Synthrotek PT2399 Delay',standard:'ANSI',revision:'v0.4',image:'',source:'https://www.synthrotek.com/wp-content/uploads/2014/02/pt2399_delay_v04.pdf',publisher:'Synthrotek',trust:'open-source',review:'source-found',note:'Konkrete PT2399-Delay-Referenz mit NE5532, Delay-Length-, Feedback- und Mix-Regelung. Das ToneForge-Projekt wird auf diese Variante festgelegt, sofern BOM und Detaildaten abgeglichen sind.'}],
 'pedal:distortion-plus':[{label:'MXR Distortion Plus · LM741',standard:'ANSI',revision:'klassischer Distortion+-Effektkern',image:'https://barbarach.com/wp-content/uploads/2022/01/MXRDistPlus_LM741_Schematic.png',source:'https://barbarach.com/mxr-distortion-plus-on-breadboard/',publisher:'Barbarach BC',trust:'established-diy',review:'source-found',note:'Noch nicht als Original-Serviceunterlage verifiziert.'}],
 'pedal:vox-v847':[{label:'Vox V847 Wah-Wah',standard:'ANSI',revision:'klassische V847-Topologie',image:'',source:'https://www.electrosmash.com/vox-v847-analysis',publisher:'ElectroSmash',trust:'established-diy',review:'source-found',note:'500-mH-Induktor und 100-kΩ-Wah-Poti sind Teil der dokumentierten Referenz. Revision und Transistorbestückung vor Replikation abgleichen.'}],
 'pedal:rangemaster':[{label:'Dallas Rangemaster Treble Booster',standard:'ANSI',revision:'klassische PNP-Germanium-Topologie',image:'',source:'https://www.electrosmash.com/dallas-rangemaster',publisher:'ElectroSmash',trust:'established-diy',review:'source-found',note:'Positive-Ground-/PNP-Kontext sowie OC44-Ersatz und Pinout ausdrücklich prüfen.'}],
 'pedal:tone-bender-mkii':[{label:'Sola Sound Tone Bender MKII Professional',standard:'ANSI',revision:'MKII Professional Referenz',image:'',source:'https://www.pcbway.com/project/shareproject/Sola_Sound_Tone_Bender_MKII_0fbac07d.html',publisher:'PCBWay Community · Dee Curtis',trust:'open-source',review:'candidate',note:'Open-Source CAD/PCB-Projekt unter CC BY-SA. Vor Hochstufung auf gegengeprüft gegen historische MKII-Referenzen und konkrete Germaniumbestückung vergleichen.'}],
 'pedal:green-ringer':[{label:'Dan Armstrong Green Ringer',standard:'ANSI',revision:'GGG Vintage Replica',image:'',source:'https://generalguitargadgets.com/how-to-build-it/technical-help/schematics/',publisher:'General Guitar Gadgets',trust:'established-diy',review:'source-found',note:'GGG führt den Dan Armstrong Green Ringer als eigenes Octave-Projekt. Konkreten Projektplan/BOM noch vollständig in ToneForge abgleichen.'}],
 'pedal:ea-tremolo':[{label:'EA Tremolo · Modified',standard:'ANSI',revision:'GGG 2006-08-12',image:'',source:'https://generalguitargadgets.com/pdf/ggg_eatrem_mod_lo.pdf',publisher:'General Guitar Gadgets',trust:'established-diy',review:'source-found',note:'Der GGG-Plan darf laut Dokument nicht von anderen Sites neu gehostet werden; ToneForge verlinkt deshalb nur auf die Originalquelle.'}],
 'pedal:micro-amp':[{label:'MXR Micro Amp',standard:'ANSI',revision:'klassische TL061-Topologie',image:'https://www.electrosmash.com/images/tech/microamp/mxr-microamp-schematic.png',source:'https://www.electrosmash.com/mxr-microamp',publisher:'ElectroSmash',trust:'established-diy',review:'crosschecked',note:'Schaltung mit TL061, 500-kΩ-Gain-Poti und 4,5-V-Bias. Gegen die konkrete gewünschte MXR-Revision abgleichen.'}],
 'wiring:treble-bleed':[{label:'Treble-Bleed · Kondensator und Parallelwiderstand',standard:'WIRING',revision:'Volume-Poti · parallele RC-Variante',image:'https://www.guitar-mod.com/images/treble_bleed/treble_retention_w_res.jpg',source:'https://www.guitar-mod.com/rg_diag_treble_bleed.html',publisher:'Rothstein Guitars',trust:'established-diy',review:'crosschecked'}],
 'wiring:kill-switch':[{label:'Momentary Kill Switch / Output Mute',standard:'WIRING',revision:'Normally-open-Taster gegen Masse',image:'https://cdn11.bigcommerce.com/s-fxdzp2uudp/images/stencil/1280x1280/products/2525/5390/WIRING_MOD_SW001__23857.1471907091.jpg?c=2',source:'https://guitarelectronics.com/guitar-kill-switch-output-mute-switch/',publisher:'GuitarElectronics.com',trust:'established-diy',review:'source-found'}],
 'wiring:phase-reverse':[{label:'Pickup In Phase / Reverse Phase',standard:'WIRING',revision:'DPDT On/On · Pickup Hot/Cold umschalten',image:'https://cdn11.bigcommerce.com/s-fxdzp2uudp/images/stencil/1280x1280/products/2522/5406/In_Phase_Reverse_Phase__40362.1471991208.jpg',source:'https://guitarelectronics.com/guitar-wiring-resources/guitar-pickup-control-wiring-mods/',publisher:'GuitarElectronics.com',trust:'established-diy',review:'source-found'}],
 'wiring:coil-split':[{label:'Humbucker Coil Split',standard:'WIRING',revision:'Push/Pull · Hersteller-Farbcode erforderlich',image:'',source:'https://www.seymourduncan.com/resources/pickup/wiring-diagrams',publisher:'Seymour Duncan',trust:'manufacturer',review:'source-found',note:'Kein generisches Farbschema vortäuschen: Leiterfarben und Serienverbindung müssen zum konkreten Pickup-Hersteller passen.'}]
};
})();
